
clone_folder: c:\projects\myproject

image:
  - Visual Studio 2017

configuration:
  - Release

environment:
  matrix:
    - arch: x64

install:
  # Use the mingw-w64 provided by Appveyor (must be placed before Perl in the path)
  - cmd: SET PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\;%PATH%

build_script:
  - md build
  - cd build
  - cmake --version
  - cmake -Wno-dev -Wno-deprecated -G "MinGW Makefiles" .. -DCMAKE_SUPPRESS_REGENERATION=1
  - cmake --build . --config "%CONFIGURATION%" -- /verbosity:minimal
  #- mingw32-make.exe VERBOSE=1